#!/bin/bash
set -e


echo "Building TypeScript code..."
npm run clean
npm run build

echo "Packaging Lambda functions..."
cp -r node_modules dist/
cd dist
zip -r ../ingest-lambda.zip ingest/ node_modules/ types.js
zip -r ../worker-lambda.zip worker/ node_modules/ types.js
cd ..

echo "Initializing Terraform..."
cd terraform
terraform init

echo "Deploying infrastructure..."
terraform apply -auto-approve

echo ""
echo "Deployment complete!"
echo ""
terraform output

echo ""
echo "Saving environment variables..."
cd ..

# Get outputs from Terraform
API_ENDPOINT=$(terraform -chdir=terraform output -raw api_endpoint)
INGEST_URL=$(terraform -chdir=terraform output -raw ingest_url)
DYNAMODB_TABLE=$(terraform -chdir=terraform output -raw dynamodb_table_name)
SQS_QUEUE_URL=$(terraform -chdir=terraform output -raw sqs_queue_url)
SQS_DLQ_URL=$(terraform -chdir=terraform output -raw sqs_dlq_url)

# Create .env file
cat > .env << EOF
# Auto-generated by deploy.sh - $(date)
export API_ENDPOINT="$API_ENDPOINT"
export INGEST_URL="$INGEST_URL"
export DYNAMODB_TABLE="$DYNAMODB_TABLE"
export SQS_QUEUE_URL="$SQS_QUEUE_URL"
export SQS_DLQ_URL="$SQS_DLQ_URL"
EOF

# Export in current process (only works if script is sourced)
export API_ENDPOINT
export INGEST_URL
export DYNAMODB_TABLE
export SQS_QUEUE_URL
export SQS_DLQ_URL

echo ""
echo "Environment variables saved to .env file:"
echo "  API_ENDPOINT=$API_ENDPOINT"
echo "  INGEST_URL=$INGEST_URL"
echo "  DYNAMODB_TABLE=$DYNAMODB_TABLE"
echo "  SQS_QUEUE_URL=$SQS_QUEUE_URL"
echo "  SQS_DLQ_URL=$SQS_DLQ_URL"
echo ""
echo "To load these variables in your current shell:"
echo "  source .env"
